version: '3'

services:
  backend:
    build: ./backend-thesi-web
    ports:
      - 3000:3000
    container_name: thesi-ux-backend
    env_file:
      - .env

  frontend:
    build: ./frontend-thesi-web
    ports:
      - 5173:5173
    container_name: thesi-ux-frontend
    env_file:
      - .env
  
  database:
    image: postgres:latest  # Use a imagem oficial do Postgres
    environment:
      - DB_CONNECTION=${DB_CONNECTION}  # Carregar do arquivo .env
    container_name: thesi-ux-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistência de dados

volumes:
  postgres-data:
